---
title: "99_proj_func"
format: html
editor: visual
---

## Running Code

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
box_plot <- function(df, x_col, y_col, x_label, y_label, title) {
  b_plot <- ggplot(data = df,
                   mapping = aes(x = {{x_col}},
                                 y = {{y_col}})) + 
    geom_boxplot() +
    xlab(x_label) + 
    ylab(y_label) +
    ggtitle(title)
  
  return(b_plot)
}
```

```{r}
density_plot <- function(df, x_col, y_col, z_color, x_label, y_label, title) {
  d_plot <- ggplot(data = df,
                   mapping = aes(x = {{x_col}})) + 
    geom_density() +
    xlab(x_label) + 
    ylab(y_label) +
    ggtitle(title)
  
  return(d_plot)
}
```

```{r}
heatmap <- function(df, x_col, y_col, z_color, x_label, y_label, title) {
  h_map <- ggplot(data = df,
                   mapping = aes(x = {{x_col}},
                                 y = {{y_col}},
                                 fill = {{z_color}})) + 
    geom_tile() +
    xlab(x_label) + 
    ylab(y_label) +
    ggtitle(title)
  
  return(h_map)
}
```

```{r}
#| echo: false

box_plot(mtcars, as.factor(cyl), mpg, "xTest", "yTest", "Test title")
```

```{r}
#| echo: false

x <- LETTERS[1:20]
y <- paste0("var", seq(1,20))
data <- expand.grid(X=x, Y=y)
data$Z <- runif(400, 0, 5)

heatmap(data, X, Y, Z, "xTest", "yTest", "Title")

```


